"""
Vectors and matrices of doubles, and scalar helpers.
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['EPSILON', 'HALF_PI', 'Mat2', 'Mat3', 'Mat4', 'PI', 'TWO_PI', 'Vec2', 'Vec3', 'Vec4', 'approx_equal', 'clamp', 'cross', 'degrees', 'dot', 'lerp', 'radians', 'saturate', 'sign', 'smoothstep']
class Mat2:
    """
    A fixed-size row-major matrix; also a buffer, so numpy.asarray(m) works.
    """
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def identity() -> Mat2:
        ...
    def __add__(self, arg0: Mat2) -> Mat2:
        ...
    def __eq__(self, arg0: Mat2) -> bool:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, rows: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @typing.overload
    def __matmul__(self, arg0: Vec2) -> Vec2:
        ...
    @typing.overload
    def __matmul__(self, arg0: Mat2) -> Mat2:
        ...
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat2:
        ...
    def __ne__(self, arg0: Mat2) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat2:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Mat2) -> Mat2:
        ...
    def at(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def determinant(self) -> float:
        ...
    def inverse(self) -> Mat2:
        ...
    def transpose(self) -> Mat2:
        ...
class Mat3:
    """
    A fixed-size row-major matrix; also a buffer, so numpy.asarray(m) works.
    """
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def identity() -> Mat3:
        ...
    def __add__(self, arg0: Mat3) -> Mat3:
        ...
    def __eq__(self, arg0: Mat3) -> bool:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, rows: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @typing.overload
    def __matmul__(self, arg0: Vec3) -> Vec3:
        ...
    @typing.overload
    def __matmul__(self, arg0: Mat3) -> Mat3:
        ...
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat3:
        ...
    def __ne__(self, arg0: Mat3) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat3:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Mat3) -> Mat3:
        ...
    def at(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def determinant(self) -> float:
        ...
    def inverse(self) -> Mat3:
        ...
    def transpose(self) -> Mat3:
        ...
class Mat4:
    """
    A fixed-size row-major matrix; also a buffer, so numpy.asarray(m) works.
    """
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def identity() -> Mat4:
        ...
    def __add__(self, arg0: Mat4) -> Mat4:
        ...
    def __eq__(self, arg0: Mat4) -> bool:
        ...
    def __getitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, rows: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @typing.overload
    def __matmul__(self, arg0: Vec4) -> Vec4:
        ...
    @typing.overload
    def __matmul__(self, arg0: Mat4) -> Mat4:
        ...
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat4:
        ...
    def __ne__(self, arg0: Mat4) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Mat4:
        ...
    def __setitem__(self, arg0: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Mat4) -> Mat4:
        ...
    def at(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def transpose(self) -> Mat4:
        ...
class Vec2:
    """
    A fixed-size vector; also a buffer, so numpy.asarray(v) works.
    """
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: Vec2) -> Vec2:
        ...
    def __eq__(self, arg0: Vec2) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, value: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, values: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec2:
        ...
    @typing.overload
    def __mul__(self, arg0: Vec2) -> Vec2:
        ...
    def __ne__(self, arg0: Vec2) -> bool:
        ...
    def __neg__(self) -> Vec2:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec2:
        ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Vec2) -> Vec2:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec2:
        ...
    @typing.overload
    def __truediv__(self, arg0: Vec2) -> Vec2:
        ...
    def distance(self, other: Vec2) -> float:
        ...
    def distance_squared(self, other: Vec2) -> float:
        ...
    def length(self) -> float:
        ...
    def length_squared(self) -> float:
        ...
    def mean(self) -> float:
        ...
    def normalized(self) -> Vec2:
        ...
    def sum(self) -> float:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Vec3:
    """
    A fixed-size vector; also a buffer, so numpy.asarray(v) works.
    """
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: Vec3) -> Vec3:
        ...
    def __eq__(self, arg0: Vec3) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, value: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, values: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec3:
        ...
    @typing.overload
    def __mul__(self, arg0: Vec3) -> Vec3:
        ...
    def __ne__(self, arg0: Vec3) -> bool:
        ...
    def __neg__(self) -> Vec3:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec3:
        ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Vec3) -> Vec3:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec3:
        ...
    @typing.overload
    def __truediv__(self, arg0: Vec3) -> Vec3:
        ...
    def distance(self, other: Vec3) -> float:
        ...
    def distance_squared(self, other: Vec3) -> float:
        ...
    def length(self) -> float:
        ...
    def length_squared(self) -> float:
        ...
    def mean(self) -> float:
        ...
    def normalized(self) -> Vec3:
        ...
    def sum(self) -> float:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Vec4:
    """
    A fixed-size vector; also a buffer, so numpy.asarray(v) works.
    """
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: Vec4) -> Vec4:
        ...
    def __eq__(self, arg0: Vec4) -> bool:
        ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, value: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, values: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsFloat | typing.SupportsIndex, arg3: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec4:
        ...
    @typing.overload
    def __mul__(self, arg0: Vec4) -> Vec4:
        ...
    def __ne__(self, arg0: Vec4) -> bool:
        ...
    def __neg__(self) -> Vec4:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec4:
        ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def __sub__(self, arg0: Vec4) -> Vec4:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vec4:
        ...
    @typing.overload
    def __truediv__(self, arg0: Vec4) -> Vec4:
        ...
    def distance(self, other: Vec4) -> float:
        ...
    def distance_squared(self, other: Vec4) -> float:
        ...
    def length(self) -> float:
        ...
    def length_squared(self) -> float:
        ...
    def mean(self) -> float:
        ...
    def normalized(self) -> Vec4:
        ...
    def sum(self) -> float:
        ...
    @property
    def w(self) -> float:
        ...
    @w.setter
    def w(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
@typing.overload
def approx_equal(a: Vec2, b: Vec2, epsilon: typing.SupportsFloat | typing.SupportsIndex = 1e-05) -> bool:
    ...
@typing.overload
def approx_equal(a: Vec3, b: Vec3, epsilon: typing.SupportsFloat | typing.SupportsIndex = 1e-05) -> bool:
    ...
@typing.overload
def approx_equal(a: Vec4, b: Vec4, epsilon: typing.SupportsFloat | typing.SupportsIndex = 1e-05) -> bool:
    ...
@typing.overload
def approx_equal(a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, epsilon: typing.SupportsFloat | typing.SupportsIndex = 1e-05) -> bool:
    ...
def clamp(value: typing.SupportsFloat | typing.SupportsIndex, low: typing.SupportsFloat | typing.SupportsIndex, high: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def cross(a: Vec3, b: Vec3) -> Vec3:
    ...
def degrees(radians: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
@typing.overload
def dot(a: Vec2, b: Vec2) -> float:
    ...
@typing.overload
def dot(a: Vec3, b: Vec3) -> float:
    ...
@typing.overload
def dot(a: Vec4, b: Vec4) -> float:
    ...
@typing.overload
def lerp(a: Vec2, b: Vec2, t: typing.SupportsFloat | typing.SupportsIndex) -> Vec2:
    ...
@typing.overload
def lerp(a: Vec3, b: Vec3, t: typing.SupportsFloat | typing.SupportsIndex) -> Vec3:
    ...
@typing.overload
def lerp(a: Vec4, b: Vec4, t: typing.SupportsFloat | typing.SupportsIndex) -> Vec4:
    ...
@typing.overload
def lerp(a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, t: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def radians(degrees: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def saturate(value: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def sign(value: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
def smoothstep(edge0: typing.SupportsFloat | typing.SupportsIndex, edge1: typing.SupportsFloat | typing.SupportsIndex, x: typing.SupportsFloat | typing.SupportsIndex) -> float:
    ...
EPSILON: float = 1e-05
HALF_PI: float = 1.5707963267948966
PI: float = 3.141592653589793
TWO_PI: float = 6.283185307179586
