from collections.abc import Callable, Sequence
from typing import Any, ClassVar

from . import assertions as assertions
from . import log as log

class OryxError(Exception):
    detail: str

class ParamError(OryxError):
    key: str

class ScriptError(OryxError): ...
class OryxAssertionError(OryxError): ...

ParamValue = bool | int | float | str

class ActionFeatures:
    def decode(self, action: int) -> list[int]: ...

class StateHandle:
    def legal_actions(self) -> list[int]: ...
    def apply(self, action: int) -> None: ...
    def undo(self, action: int) -> None: ...
    def current_player(self) -> int: ...
    def is_terminal(self) -> bool: ...
    def outcome(self) -> list[float]: ...
    def action_to_string(self, action: int) -> str: ...

class GameHandle:
    def name(self) -> str: ...
    def num_players(self) -> int: ...
    def new_initial_state(self) -> StateHandle: ...

class StrategyHandle: ...

class Context:
    @property
    def state(self) -> StateHandle: ...
    @property
    def action_features(self) -> ActionFeatures | None: ...

class State:
    def action_to_string(self, action: int) -> str: ...

class Game:
    num_players: ClassVar[int]
    name: ClassVar[str]

    def __init_subclass__(cls, *, id: str | None = None, overwrite: bool = False) -> None: ...
    def new_initial_state(self) -> State: ...

class Strategy:
    def __init_subclass__(cls, *, id: str | None = None, overwrite: bool = False) -> None: ...
    def decide(self, context: Context) -> int: ...

GameLike = str | GameHandle | Game
StrategyLike = str | StrategyHandle | Strategy

class Match:
    def __init__(self, game: GameLike, strategies: Sequence[StrategyLike]) -> None: ...
    def state(self) -> StateHandle: ...
    def is_terminal(self) -> bool: ...
    def current_player(self) -> int: ...
    def outcome(self) -> list[float]: ...
    def decide(self) -> int: ...
    def apply(self, action: int) -> None: ...
    def undo(self) -> int | None: ...
    def redo(self) -> int | None: ...
    def play(self) -> list[float]: ...
    def history(self) -> list[int]: ...

class BatchResult:
    @property
    def matches(self) -> int: ...
    @property
    def wins(self) -> list[int]: ...
    @property
    def draws(self) -> int: ...
    @property
    def rewards(self) -> list[float]: ...
    @property
    def decisions(self) -> int: ...

class BatchRunner:
    def __init__(self, game: GameLike, strategies: Sequence[StrategyLike]) -> None: ...
    def run(self, matches: int) -> BatchResult: ...

class Random:
    def __init__(self, seed: int | None = None) -> None: ...
    def seed(self, seed: int) -> None: ...
    def get_int(self, min: int = 0, max: int = ...) -> int: ...
    def get_double(self, min: float = 0.0, max: float = 1.0) -> float: ...
    def get_bool(self, p: float = 0.5) -> bool: ...

def make_game(name: str, **params: ParamValue) -> GameHandle: ...
def make_strategy(name: str, **params: ParamValue) -> StrategyHandle: ...
def list_games() -> list[str]: ...
def list_strategies() -> list[str]: ...
def describe_game(name: str) -> dict[str, Any]: ...
def describe_strategy(name: str) -> dict[str, Any]: ...
def register_game(
    id: str,
    factory: Callable[..., Game],
    params: dict[str, ParamValue | type[ParamValue]] | None = None,
    description: str = "",
    overwrite: bool = False,
) -> None: ...
def register_strategy(
    id: str,
    factory: Callable[..., Strategy],
    params: dict[str, ParamValue | type[ParamValue]] | None = None,
    description: str = "",
    overwrite: bool = False,
) -> None: ...
def simulate(game: GameLike, strategies: Sequence[StrategyLike], games: int = 1000, seed: int | None = None) -> BatchResult: ...
