import os
import sys
import sysconfig
from pathlib import Path

import pytest

from build_system.config import BuildConfig
from build_system.setup import python_env


@pytest.mark.parametrize(
    ("ldlibrary", "ldversion", "file_name", "stem"),
    [
        ("libpython3.11.so.1.0", "3.11", "libpython3.11.so.1.0", "python3.11"),
        ("libpython3.11d.so", "3.11d", "libpython3.11d.so", "python3.11d"),
        ("libpython3.13.dylib", "3.13", "libpython3.13.dylib", "python3.13"),
        ("Python.framework/Versions/3.11/Python", "3.11", "libpython3.11.dylib", "python3.11"),
        ("libpython3.11.a", "3.11", "libpython3.11.a", "python3.11"),
    ],
)
def test_unix_library_stem(monkeypatch, ldlibrary, ldversion, file_name, stem):
    variables = {"LDLIBRARY": ldlibrary, "LDVERSION": ldversion}
    monkeypatch.setattr(sysconfig, "get_config_var", variables.get)
    assert python_env._unix_library(Path("/lib")) == (Path("/lib") / file_name, stem)


def test_windows_library():
    name = f"python{sys.version_info.major}{sys.version_info.minor}"
    assert python_env._windows_library(Path("C:/py/libs")) == (Path("C:/py/libs") / f"{name}.lib", name)


def test_premake_options_without_python():
    assert python_env.premake_python_options(BuildConfig(python_enabled=False)) == ["--no-python"]


def test_premake_options_with_python(fake_python):
    assert python_env.premake_python_options(BuildConfig()) == [
        "--python-include=/py/include/python3.11",
        "--python-libdir=/py/lib",
        "--python-lib=python3.11",
    ]


def test_write_python_config_only_when_changed(tmp_project):
    info = python_env.PythonBuildInfo(
        include_dir=Path("/py/include"),
        lib_dir=Path("/py/lib"),
        lib_name="python3.11",
        home=Path('/odd "home"\\dir'),
        site_packages=(Path("/a/site-packages"), Path("/b/site-packages")),
    )
    header = tmp_project / "build" / "generated" / "PythonConfig.h"
    assert python_env.write_python_config(info) is True
    home = Path('/odd "home"\\dir').as_posix().replace("\\", "\\\\").replace('"', '\\"')
    assert header.read_text(encoding="utf-8") == (
        "#pragma once\n\n"
        "// Generated by `uv run forge`: the interpreter the embedded runtime starts.\n"
        f'#define OX_PYTHON_HOME "{home}"\n'
        f'#define OX_PYTHON_SITE_PACKAGES "/a/site-packages{os.pathsep}/b/site-packages"\n'
    )
    assert python_env.write_python_config(info) is False


def test_python_build_info_rejects_static_libpython(tmp_path, monkeypatch, linux_host):
    include = tmp_path / "include"
    include.mkdir()
    (include / "Python.h").touch()
    (tmp_path / "libpython3.11.a").touch()
    variables = {"INCLUDEPY": str(include), "LIBDIR": str(tmp_path), "LDLIBRARY": "libpython3.11.a", "LDVERSION": "3.11"}
    monkeypatch.setattr(sysconfig, "get_config_var", variables.get)
    with pytest.raises(python_env.PythonEnvError, match="No shared libpython"):
        python_env.python_build_info()
