from typing import ClassVar

class ActionFeatures:
    def decode(self, action: int) -> list[int]: ...

class StateHandle:
    def legal_actions(self) -> list[int]: ...
    def apply(self, action: int) -> None: ...
    def undo(self, action: int) -> None: ...
    def current_player(self) -> int: ...
    def is_terminal(self) -> bool: ...
    def outcome(self) -> list[float]: ...
    def action_to_string(self, action: int) -> str: ...

class GameHandle:
    def name(self) -> str: ...
    def num_players(self) -> int: ...
    def new_initial_state(self) -> StateHandle: ...

class StrategyHandle: ...

class Context:
    @property
    def state(self) -> StateHandle: ...
    @property
    def action_features(self) -> ActionFeatures | None: ...

class State:
    def action_to_string(self, action: int) -> str: ...

class Game:
    num_players: ClassVar[int]
    name: ClassVar[str]

    def __init_subclass__(cls, *, id: str | None = None, overwrite: bool = False) -> None: ...
    def new_initial_state(self) -> State: ...

class Strategy:
    def __init_subclass__(cls, *, id: str | None = None, overwrite: bool = False) -> None: ...
    def decide(self, context: Context) -> int: ...
