import logging

def trace(message: str) -> None: ...
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...
def critical(message: str) -> None: ...

class Handler(logging.Handler):
    def __init__(self, level: int = ...) -> None: ...
    def emit(self, record: logging.LogRecord) -> None: ...

def install(logger: logging.Logger | None = None, level: int = ...) -> Handler: ...
