from collections.abc import Sequence
from typing import overload

PI: float
TWO_PI: float
HALF_PI: float
EPSILON: float

class Vec2:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, values: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    x: float
    y: float
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __neg__(self) -> Vec2: ...
    def __add__(self, other: Vec2) -> Vec2: ...
    def __sub__(self, other: Vec2) -> Vec2: ...
    @overload
    def __mul__(self, other: float) -> Vec2: ...
    @overload
    def __mul__(self, other: Vec2) -> Vec2: ...
    def __rmul__(self, scalar: float) -> Vec2: ...
    @overload
    def __truediv__(self, other: float) -> Vec2: ...
    @overload
    def __truediv__(self, other: Vec2) -> Vec2: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def normalized(self) -> Vec2: ...
    def distance(self, other: Vec2) -> float: ...
    def distance_squared(self, other: Vec2) -> float: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...

class Vec3:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, values: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    x: float
    y: float
    z: float
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __neg__(self) -> Vec3: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    @overload
    def __mul__(self, other: float) -> Vec3: ...
    @overload
    def __mul__(self, other: Vec3) -> Vec3: ...
    def __rmul__(self, scalar: float) -> Vec3: ...
    @overload
    def __truediv__(self, other: float) -> Vec3: ...
    @overload
    def __truediv__(self, other: Vec3) -> Vec3: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def normalized(self) -> Vec3: ...
    def distance(self, other: Vec3) -> float: ...
    def distance_squared(self, other: Vec3) -> float: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...

class Vec4:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, values: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    x: float
    y: float
    z: float
    w: float
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __neg__(self) -> Vec4: ...
    def __add__(self, other: Vec4) -> Vec4: ...
    def __sub__(self, other: Vec4) -> Vec4: ...
    @overload
    def __mul__(self, other: float) -> Vec4: ...
    @overload
    def __mul__(self, other: Vec4) -> Vec4: ...
    def __rmul__(self, scalar: float) -> Vec4: ...
    @overload
    def __truediv__(self, other: float) -> Vec4: ...
    @overload
    def __truediv__(self, other: Vec4) -> Vec4: ...
    def length(self) -> float: ...
    def length_squared(self) -> float: ...
    def normalized(self) -> Vec4: ...
    def distance(self, other: Vec4) -> float: ...
    def distance_squared(self, other: Vec4) -> float: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...

class Mat2:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rows: Sequence[Sequence[float]]) -> None: ...
    @staticmethod
    def identity() -> Mat2: ...
    def at(self, row: int, col: int) -> float: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __add__(self, other: Mat2) -> Mat2: ...
    def __sub__(self, other: Mat2) -> Mat2: ...
    def __mul__(self, scalar: float) -> Mat2: ...
    def __rmul__(self, scalar: float) -> Mat2: ...
    @overload
    def __matmul__(self, other: Mat2) -> Mat2: ...
    @overload
    def __matmul__(self, other: Vec2) -> Vec2: ...
    def transpose(self) -> Mat2: ...
    def determinant(self) -> float: ...
    def inverse(self) -> Mat2: ...

class Mat3:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rows: Sequence[Sequence[float]]) -> None: ...
    @staticmethod
    def identity() -> Mat3: ...
    def at(self, row: int, col: int) -> float: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __add__(self, other: Mat3) -> Mat3: ...
    def __sub__(self, other: Mat3) -> Mat3: ...
    def __mul__(self, scalar: float) -> Mat3: ...
    def __rmul__(self, scalar: float) -> Mat3: ...
    @overload
    def __matmul__(self, other: Mat3) -> Mat3: ...
    @overload
    def __matmul__(self, other: Vec3) -> Vec3: ...
    def transpose(self) -> Mat3: ...
    def determinant(self) -> float: ...
    def inverse(self) -> Mat3: ...

class Mat4:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rows: Sequence[Sequence[float]]) -> None: ...
    @staticmethod
    def identity() -> Mat4: ...
    def at(self, row: int, col: int) -> float: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __add__(self, other: Mat4) -> Mat4: ...
    def __sub__(self, other: Mat4) -> Mat4: ...
    def __mul__(self, scalar: float) -> Mat4: ...
    def __rmul__(self, scalar: float) -> Mat4: ...
    @overload
    def __matmul__(self, other: Mat4) -> Mat4: ...
    @overload
    def __matmul__(self, other: Vec4) -> Vec4: ...
    def transpose(self) -> Mat4: ...

@overload
def dot(a: Vec2, b: Vec2) -> float: ...
@overload
def dot(a: Vec3, b: Vec3) -> float: ...
@overload
def dot(a: Vec4, b: Vec4) -> float: ...
def cross(a: Vec3, b: Vec3) -> Vec3: ...
@overload
def lerp(a: float, b: float, t: float) -> float: ...
@overload
def lerp(a: Vec2, b: Vec2, t: float) -> Vec2: ...
@overload
def lerp(a: Vec3, b: Vec3, t: float) -> Vec3: ...
@overload
def lerp(a: Vec4, b: Vec4, t: float) -> Vec4: ...
@overload
def approx_equal(a: float, b: float, epsilon: float = ...) -> bool: ...
@overload
def approx_equal(a: Vec2, b: Vec2, epsilon: float = ...) -> bool: ...
@overload
def approx_equal(a: Vec3, b: Vec3, epsilon: float = ...) -> bool: ...
@overload
def approx_equal(a: Vec4, b: Vec4, epsilon: float = ...) -> bool: ...
def clamp(value: float, low: float, high: float) -> float: ...
def saturate(value: float) -> float: ...
def sign(value: float) -> float: ...
def smoothstep(edge0: float, edge1: float, x: float) -> float: ...
def radians(degrees: float) -> float: ...
def degrees(radians: float) -> float: ...
