class Random:
    def __init__(self, seed: int | None = None) -> None: ...
    def seed(self, seed: int) -> None: ...
    def get_int(self, min: int = 0, max: int = ...) -> int: ...
    def get_double(self, min: float = 0.0, max: float = 1.0) -> float: ...
    def get_bool(self, p: float = 0.5) -> bool: ...
