from collections.abc import Sequence

from .game import Game, GameHandle, StateHandle, Strategy, StrategyHandle

GameLike = str | GameHandle | Game
StrategyLike = str | StrategyHandle | Strategy

class Match:
    def __init__(self, game: GameLike, strategies: Sequence[StrategyLike]) -> None: ...
    def state(self) -> StateHandle: ...
    def is_terminal(self) -> bool: ...
    def current_player(self) -> int: ...
    def outcome(self) -> list[float]: ...
    def decide(self) -> int: ...
    def apply(self, action: int) -> None: ...
    def undo(self) -> int | None: ...
    def redo(self) -> int | None: ...
    def play(self) -> list[float]: ...
    def history(self) -> list[int]: ...

class BatchResult:
    @property
    def matches(self) -> int: ...
    @property
    def wins(self) -> list[int]: ...
    @property
    def draws(self) -> int: ...
    @property
    def rewards(self) -> list[float]: ...
    @property
    def decisions(self) -> int: ...

class BatchRunner:
    def __init__(self, game: GameLike, strategies: Sequence[StrategyLike]) -> None: ...
    def run(self, matches: int) -> BatchResult: ...

def simulate(game: GameLike, strategies: Sequence[StrategyLike], games: int = 1000, seed: int | None = None) -> BatchResult: ...
