#!/usr/bin/env python3
"""Embeds every .msl under the shader root into a generated C++ file, keyed by "/Oryx/<relative path>".

Output is deterministic (sorted paths, no timestamps) and rewritten only when it changes.
Usage: embed_shaders.py <shader_root> <output.cpp> [--check]
"""
import pathlib
import sys

PER_LINE = 24


def render(root: pathlib.Path) -> str:
    out = [
        '// Generated by Oryx/tools/embed_shaders.py from Oryx/shaders; do not edit.',
        '#include "oxpch.h"',
        '#include "Oryx/Shaders/Source/ShaderSourceProvider.h"',
        '',
        'namespace oryx',
        '{',
        '',
        'namespace',
        '{',
        '',
    ]
    registrars = []
    for index, file in enumerate(sorted(p for p in root.rglob('*') if p.suffix in ('.msl', '.slang'))):
        virtual = '/Oryx/' + file.relative_to(root).as_posix()
        data = file.read_bytes().replace(b'\r\n', b'\n')
        out.append(f'// {virtual}')
        out.append(f'constexpr char SHADER_{index}[] = {{')
        for start in range(0, len(data), PER_LINE):
            out.append('    ' + ', '.join(str(b) for b in data[start:start + PER_LINE]) + ',')
        out.append('};')
        out.append('')
        registrars.append(f'const EmbeddedShaderRegistrar REGISTRAR_{index}("{virtual}", SHADER_{index}, sizeof(SHADER_{index}));')
    out += registrars
    out += ['', '} // namespace', '', '} // namespace oryx', '']
    return '\n'.join(out)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    root = pathlib.Path(sys.argv[1])
    target = pathlib.Path(sys.argv[2])
    text = render(root)
    current = target.read_text() if target.exists() else None
    if '--check' in sys.argv:
        if current != text:
            print(f'{target} is stale; run tools/embed_shaders.py', file=sys.stderr)
            return 1
        return 0
    if current != text:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
