import subprocess
from pathlib import Path

import typer
from rich.console import Console
from rich.markup import escape

from .. import options
from ..config import RunContext
from ..project import Project
from ..utils import run_command, write_text_lf

console = Console()


def premake_args(run: RunContext) -> list[str]:
    """Every Premake flag this run's options produce, in a stable order (their hash decides an output wipe)."""
    try:
        plugin_args = [arg for result in run.pm.hook.forge_premake_args(ctx=run) if result for arg in result]
    except RuntimeError as error:
        console.print(f"[bold red]✗ {escape(str(error))}[/bold red]")
        raise typer.Exit(code=1)
    return options.premake_flags(run.config.options, run.options, run.defines) + plugin_args


LUA_DIR = Path(__file__).resolve().parent.parent / "lua"
LUA_FRAGMENTS = ("export", "dependencies", "toolchain")
FORGE_LUA_HEADER = "-- Generated by `forge configure` from pyforge's lua/ fragments; do not edit (gitignored).\n"


def render_forge_lua(project: Project, lua_dir: Path = LUA_DIR) -> Path:
    """Bundle the lua/ fragments into <project>/premake/forge.lua; rewritten only when its content changes."""
    fragments = [f"do\n{(lua_dir / f'{name}.lua').read_text(encoding='utf-8').rstrip()}\nend\n" for name in LUA_FRAGMENTS]
    text = FORGE_LUA_HEADER + "\n" + "\n".join(fragments)
    path = project.root / "premake" / "forge.lua"
    if not path.is_file() or path.read_text(encoding="utf-8") != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_text_lf(path, text)
    return path


def export_command(executable: Path, generator: str, premake_options: list[str]) -> list[str]:
    return [str(executable), generator, *premake_options, "--forge-export"]


def run_export(executable: Path, generator: str, premake_options: list[str], project: Project, verbose: bool = False) -> None:
    render_forge_lua(project)
    try:
        with console.status("[bold blue]⚙️ Configuring build...[/bold blue]"):
            result = run_command(export_command(executable, generator, premake_options), cwd=project.root)
        if verbose and result.stdout:
            console.print(result.stdout)
        console.print("[bold green]✓ Build files generated successfully.[/bold green]\n")
    except subprocess.CalledProcessError as error:
        console.print(f"[bold red]✗ Failed to configure build:[/bold red]\n{error.stderr}")
        raise typer.Exit(code=1)
