"""Locate the Python that Oryx's embedded scripting backend builds against.

Read from the interpreter running build_system (the uv venv), so the headers, libpython and
standard library the C++ side links are the ones `uv run` uses. The values reach Premake as
the --python-* options declared in premake/python.lua, except the interpreter's home and
site-packages, which go into a generated header only PythonRuntime.cpp includes.
"""

from dataclasses import dataclass
import os
from pathlib import Path
import platform
import sys
import sysconfig

from build_system.config import BUILD_DIR, BuildConfig


class PythonEnvError(RuntimeError):
    pass


@dataclass(frozen=True)
class PythonBuildInfo:
    include_dir: Path
    lib_dir: Path
    lib_name: str
    home: Path
    site_packages: tuple[Path, ...]


_NO_LIBPYTHON_HINT = "Use `uv run forge --no-python ...`, or a Python built with a shared libpython."


def _windows_library(lib_dir: Path) -> tuple[Path, str]:
    name = f"python{sys.version_info.major}{sys.version_info.minor}"
    return lib_dir / f"{name}.lib", name


def _unix_library(lib_dir: Path) -> tuple[Path, str]:
    file_name = sysconfig.get_config_var("LDLIBRARY") or ""
    if ".framework/" in file_name:
        # A framework build names its library "Python.framework/.../Python"; it also ships a plain libpythonX.Y.dylib in LIBDIR.
        file_name = f"libpython{sysconfig.get_config_var('LDVERSION') or ''}.dylib"
    stem = file_name.removeprefix("lib").split(".so")[0].removesuffix(".dylib").removesuffix(".a")
    return lib_dir / file_name, stem


def _site_packages() -> tuple[Path, ...]:
    paths = sysconfig.get_paths()
    return tuple(dict.fromkeys(Path(paths[key]) for key in ("purelib", "platlib")))


def python_build_info() -> PythonBuildInfo:
    home = Path(sys.base_prefix)
    include_dir = Path(sysconfig.get_config_var("INCLUDEPY") or sysconfig.get_paths()["include"])

    if platform.system() == "Windows":
        lib_dir = home / "libs"
        library, lib_name = _windows_library(lib_dir)
    else:
        lib_dir = Path(sysconfig.get_config_var("LIBDIR") or home / "lib")
        library, lib_name = _unix_library(lib_dir)

    if not (include_dir / "Python.h").is_file():
        raise PythonEnvError(f"Python.h not found in {include_dir}. {_NO_LIBPYTHON_HINT}")
    if not library.is_file() or library.suffix == ".a":
        raise PythonEnvError(f"No shared libpython at {library}. {_NO_LIBPYTHON_HINT}")

    return PythonBuildInfo(include_dir=include_dir, lib_dir=lib_dir, lib_name=lib_name, home=home, site_packages=_site_packages())


def premake_python_options(cfg: BuildConfig) -> list[str]:
    if not cfg.python_enabled:
        return ["--no-python"]

    info = python_build_info()
    return [
        f"--python-include={info.include_dir.as_posix()}",
        f"--python-libdir={info.lib_dir.as_posix()}",
        f"--python-lib={info.lib_name}",
    ]


PYTHON_CONFIG_HEADER = BUILD_DIR / "generated" / "PythonConfig.h"


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_python_config(info: PythonBuildInfo) -> bool:
    """Write the header PythonRuntime.cpp includes; leaves the file alone when nothing changed,
    so an unchanged interpreter never rebuilds it. Returns whether it was written."""
    text = (
        "#pragma once\n\n"
        "// Generated by `uv run forge`: the interpreter the embedded runtime starts.\n"
        f"#define OX_PYTHON_HOME {_c_string(info.home.as_posix())}\n"
        f"#define OX_PYTHON_SITE_PACKAGES {_c_string(os.pathsep.join(path.as_posix() for path in info.site_packages))}\n"
    )
    if PYTHON_CONFIG_HEADER.is_file() and PYTHON_CONFIG_HEADER.read_text(encoding="utf-8") == text:
        return False

    PYTHON_CONFIG_HEADER.parent.mkdir(parents=True, exist_ok=True)
    PYTHON_CONFIG_HEADER.write_text(text, encoding="utf-8")
    return True
